// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmzWvgCXqx55tQwLJbX1kfcouRCUAopQU',
    appId: '1:736871072234:web:0116cc856b03e68d91f293',
    messagingSenderId: '736871072234',
    projectId: 'ditonton-7e17d',
    authDomain: 'ditonton-7e17d.firebaseapp.com',
    storageBucket: 'ditonton-7e17d.firebasestorage.app',
    measurementId: 'G-SKD9EHPXQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnAV6dCEbuJoqgURKnuTE7MMSfgZ42_M',
    appId: '1:736871072234:android:7b51ddb27d2e68f291f293',
    messagingSenderId: '736871072234',
    projectId: 'ditonton-7e17d',
    storageBucket: 'ditonton-7e17d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1F1UzAqPvaVie4tLJaDv1HB_cMwbzpcw',
    appId: '1:736871072234:ios:3787036a1cf0dfce91f293',
    messagingSenderId: '736871072234',
    projectId: 'ditonton-7e17d',
    storageBucket: 'ditonton-7e17d.firebasestorage.app',
    iosBundleId: 'com.example.ditonton',
  );
}
