name: Flutter CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  analyze-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: stable
          cache: true

      - name: Check Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Analyzer
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run Tests
        run: flutter test --coverage

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info